version: '3.3'
services:
  configurador:
    image: panatta2/autoconsciencia_iot
    ports:
      - "80:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_SCHEMA=schema
    restart: always # run as a service
